name: day01
version: 0.0.1
synopsis: Advent of Code 2019
description: Day 01
maintainer: Jairinho <t4ngz3r0@gmail.com>
github: haskellicious/aoc2019

dependencies:
  - base >= 4.12.0.0 && < 4.14

library:
  source-dirs: src
  exposed-modules:
    - Day01.PartOne
    - Day01.PartTwo

tests:
  unit:
    main: Day01.hs
    source-dirs: tests
    dependencies:
      - day01
      - HUnit