name: CI

on: [push]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        stack: 
          - "2.3.1"
        ghc:
          - "8.8.3"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - name: Test
      run: |
        stack config set system-ghc --global true
        stack test
